export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOGIN_TEACHER_SUCCESS = 'LOGIN_TEACHER_SUCCESS';
export const LOGIN_STUDENT_SUCCESS = 'LOGIN_STUDENT_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';