export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOGIN_TEACHER_SUCCESS = 'LOGIN_TEACHER_SUCCESS';
export const LOGIN_STUDENT_SUCCESS = 'LOGIN_STUDENT_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const LOAD_LESSONS_SUCCESS = 'LOAD_LESSONS_SUCCESS';
export const CREATE_LESSON_SUCCESS = 'CREATE_LESSON_SUCCESS';
export const UPDATE_LESSON_SUCCESS = 'UPDATE_LESSON_SUCCESS';
export const DELETE_LESSON_SUCCESS = 'DELETE_LESSON_SUCCESS';

export const LOAD_STUDENT_LESSON_ANSWERS_FOR_A_STUDENT_SUCCESS = 'LOAD_STUDENT_LESSON_ANSWERS_FOR_A_STUDENT_SUCCESS';
export const UPDATE_STUDENT_LESSON_ANSWER = 'UPDATE_STUDENT_LESSON_ANSWER';